#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
#Description
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

#Example
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.

#Complexity
Time: O(n*logn)
"""


class Solution(object):
	def findTheDifference(self, s, t):
		"""
		:type s: str
		:type t: str
		:rtype: str
		"""
		s = sorted(list(s))
		t = sorted(list(t))
		for i in range(len(s)):
			if s[i] != t[i]:
				return t[i]
		return t[-1]

if __name__ == '__main__':
	s = 'abcd'
	t = 'abcde'
	solution = Solution()
	print solution.findTheDifference(s, t)

